HW done
Dimon23114/HW-Node pull request #1
Opened 2023-03-15 19:48 UTC by Dimon23114

2023-03-15 20:18 UTC, KhYulian requested changes
Потрібні правки

2023-03-15 20:18 UTC, KhYulian commented on models/contacts.js
> +});
винесіть в окремий файл e.g. utils/validation.js

2023-03-15 20:18 UTC, KhYulian commented on models/contacts.js
> +const listContacts = async (req, res, next) => {
listContacts => getContacts

2023-03-15 20:18 UTC, KhYulian commented on models/contacts.js
> +    if (validation.error) {
```suggestion
    const {error}= schema.validate(req.body);

    if (error) {
```

2023-03-15 20:18 UTC, KhYulian commented on models/contacts.js
> +    }
```suggestion
    contact.name = name || contact.name
    ...
    ...
```

2023-03-25 16:26 UTC, Dimon23114 commented
added changed

2023-03-25 17:17 UTC, Dimon23114 commented on models/contacts.js
> +});
+

2023-03-25 17:17 UTC, Dimon23114 commented on models/contacts.js
> +    if (validation.error) {
+

2023-03-25 17:18 UTC, Dimon23114 commented on models/contacts.js
> +const listContacts = async (req, res, next) => {
не зовсім зрозумів що потрібно зробити(

2023-03-25 17:26 UTC, KhYulian commented on models/contacts.js
> +const listContacts = async (req, res, next) => {
перейменувати)

2023-03-25 17:27 UTC, KhYulian approved these changes
Чудова робота!

2023-03-25 17:27 UTC, merged